from __future__ import annotations

from urllib.parse import urlsplit, urlunsplit

CHANNEL_URLS = [
    "https://www.youtube.com/@MarianoTrejo",
    "https://www.youtube.com/@la_inteligencia_artificial",
    "https://www.youtube.com/@humphrey",
    "https://www.youtube.com/@MisPropiasFinanzas",
    "https://www.youtube.com/@AdriàSolàPastor",
    "https://www.youtube.com/@EduardoRosas",
    "https://www.youtube.com/@CésarDabiánFinanzas",
    "https://www.youtube.com/@soycristinadayz",
    "https://www.youtube.com/@MorisDieck",
    "https://www.youtube.com/@AdrianSaenz",
    "https://www.youtube.com/@FinanzasparatodosYT",
    "https://www.youtube.com/@LuisMiNegocios",
    "https://www.youtube.com/@AprendizFinanciero",
    "https://www.youtube.com/@negociosyfinanzas2559",
    "https://www.youtube.com/@pequenocerdocapitalista",
    "https://www.youtube.com/@AlexHormozi",
    "https://www.youtube.com/@CalebHammer",
    "https://www.youtube.com/c/Myprimermillón",
    "https://www.youtube.com/@starterstory",
    "https://www.youtube.com/@irenealbacete",
    "https://www.youtube.com/@bulkin_uri",
    "https://www.youtube.com/@ExitoFinancieroOficial",
    "https://www.youtube.com/@compuestospodcast",
    "https://www.youtube.com/@JaimeHigueraEspanol",
    "https://www.youtube.com/@jefillysh",
    "https://www.youtube.com/@EDteam",
    "https://www.youtube.com/@LatinoSueco",
    "https://www.youtube.com/@Ter",
    "https://www.youtube.com/@doctorfision",
    "https://www.youtube.com/@EvaMariaBeristain",
    "https://www.youtube.com/@Unicoos",
    "https://www.youtube.com/@QuantumFracture",
    "https://www.youtube.com/@lagatadeschrodinger",
    "https://www.youtube.com/@CdeCiencia",
    "https://www.youtube.com/@elrobotdeplaton",
    "https://www.youtube.com/@PhysicsGirl",
    "https://www.youtube.com/@Veritasium",
    "https://www.youtube.com/@Vsauce",
    "https://www.youtube.com/@minutephysics",
    "https://www.youtube.com/@SmarterEveryDay",
    "https://www.youtube.com/@AsapSCIENCE",
    "https://www.youtube.com/@PBSSpaceTime",
    "https://www.youtube.com/@TheActionLab",
    "https://www.youtube.com/@numberphile",
    "https://www.youtube.com/@crashcourse",
    "https://www.youtube.com/@AliAbdaal",
    "https://www.youtube.com/@ThomasFrank",
    "https://www.youtube.com/@MattDAvella",
    "https://www.youtube.com/@NathanielDrew",
    "https://www.youtube.com/@LordDraugr",
    "https://www.youtube.com/@danielfelipemedina",
    "https://www.youtube.com/@omareducacionfinanciera",
    "https://www.youtube.com/@TwoMinutePapers",
    "https://www.youtube.com/@ElConsejeronocturno",
    "https://www.youtube.com/@UnaFisicaSimplificada",
    "https://www.youtube.com/@gustavo-entrala",
    "https://www.youtube.com/@ricardoalcados",
    "https://www.youtube.com/@inversioninteligente_alain",
    "https://www.youtube.com/@MIGALAD",
    "https://www.youtube.com/@paoalmontes",
    "https://www.youtube.com/c/Caf%C3%A9Kyoto",
    "https://www.youtube.com/@watop_esp",
    "https://www.youtube.com/@jefidos",
    "https://www.youtube.com/@judithtiral5713",
    "https://www.youtube.com/@ProgramadorX",
    "https://www.youtube.com/@NocheDeChicxs",
    "https://www.youtube.com/@Platzi",
    "https://www.youtube.com/@DiegoRevueltaTV",
    "https://www.youtube.com/@lunamartinezoficial",
    "https://www.youtube.com/@semo_historia",
    "https://www.youtube.com/@NateGentile7",
    "https://www.youtube.com/@DEMENTESMedia",
    "https://www.youtube.com/@FrancoPisso",
    "https://www.youtube.com/@witchcalli",
    "https://www.youtube.com/@viyaura",
    "https://www.youtube.com/@ArcadesBooks",
    "https://www.youtube.com/@DonebyLaura",
    "https://www.youtube.com/@TwoCentsPBS",
    "https://www.youtube.com/@bravosresearch",
    "https://www.youtube.com/@ThatNateBlack",
    "https://www.youtube.com/@DiegoRuzzarin",
    "https://www.youtube.com/@ManCarryingThing",
    "https://www.youtube.com/@comofuncionatunegocio",
    "https://www.youtube.com/@irenesauriox",
    "https://www.youtube.com/@98granos",
    "https://www.youtube.com/@WoshingoStreams",
    "https://www.youtube.com/@midulive",
    "https://www.youtube.com/@AleAbsolutable",
    "https://www.youtube.com/@RedditHistoriasSinFiltro",
    "https://www.youtube.com/@SantiagoAmatFinanzas",
    "https://www.youtube.com/@Brinnn",
    "https://www.youtube.com/@DrossRotzank",
    "https://www.youtube.com/@RicardoAlcaraz",
    "https://www.youtube.com/@RobPaperClips",
    "https://www.youtube.com/@RobPaperSheet",
    "https://www.youtube.com/@Pinwinsillo",
    "https://www.youtube.com/@atherion",
    "https://www.youtube.com/@ProfePiola",
    "https://www.youtube.com/@Sapienciapráctica",
    "https://www.youtube.com/@ImpulsoSupremo333",
    "https://www.youtube.com/@noctivoyt",
    "https://www.youtube.com/@Unpocomejor1",
    "https://www.youtube.com/@elWacky2",
    "https://www.youtube.com/@Sambucha",
    "https://www.youtube.com/@thefinancialfreedomgirl",
    "https://www.youtube.com/@ALXI_ESSAY",
    "https://www.youtube.com/@Landerdiazdelfresno",
    "https://www.youtube.com/@soydalto",
    "https://www.youtube.com/@ELCACHONDO",
    "https://www.youtube.com/@bravogabobravo",
    "https://www.youtube.com/@Eze.martinez",
    "https://www.youtube.com/@vidaprogramador",
    "https://www.youtube.com/@DotDager",
    "https://www.youtube.com/@elrincondeldev",
    "https://www.youtube.com/@mourede",
    "https://www.youtube.com/@FaztTech",
    "https://www.youtube.com/@bilinkis",
    "https://www.youtube.com/@ELMAIKINIDEV",
    "https://www.youtube.com/@IA_Innova",
    "https://www.youtube.com/@WesRoth",
    "https://www.youtube.com/@RingaTech",
    "https://www.youtube.com/@alejavirivera",
    "https://www.youtube.com/@FranqitoM",
    "https://www.youtube.com/@MisterKrax",
    "https://www.youtube.com/@vidamrr",
    "https://www.youtube.com/@EmprendeAprendiendo",
    "https://www.youtube.com/@KellyStamps",
    "https://www.youtube.com/@PlanetaJuan",
    "https://www.youtube.com/@CorduraArtificial",
    "https://www.youtube.com/@EsquizofreniaNatural",
    "https://www.youtube.com/@Monitorfantasma",
    "https://www.youtube.com/@dateunvlog",
    "https://www.youtube.com/@clem/videos",
    "https://www.youtube.com/@betterideas",
    "https://www.youtube.com/@jomakaze",
    "https://www.youtube.com/@KenJee_ds",
    "https://www.youtube.com/@HolaMundoDev",
    "https://www.youtube.com/@CreaYTransforma",
    "https://www.youtube.com/@TinaHuang1",
    "https://www.youtube.com/@ClaraCarmona",
    "https://www.youtube.com/@jessicafernandezgarcia",
    "https://www.youtube.com/@DonCanitro",
    "https://www.youtube.com/@AI_In_Context",
    "https://www.youtube.com/@TheDiaryOfACEO",
    "https://www.youtube.com/@GothamChess",
    "https://www.youtube.com/@DotCSV",
    "https://www.youtube.com/@derivando",
    "https://www.youtube.com/@Antroporama",
    "https://www.youtube.com/@JaimeAltozano",
    "https://www.youtube.com/@LaHiperactina",
    "https://www.youtube.com/@VisualPolitik",
    "https://www.youtube.com/@kurzgesagt",
    "https://www.youtube.com/@MarkRober",
    "https://www.youtube.com/@TomScott",
    "https://www.youtube.com/@RealEngineering",
    "https://www.youtube.com/@Wendoverproductions",
    "https://www.youtube.com/@cleoabram",
    "https://www.youtube.com/@StuffMadeHere",
    "https://www.youtube.com/@sabinehossenfelder",
    "https://www.youtube.com/@3blue1brown",
    "https://www.youtube.com/@standupmaths",
    "https://www.youtube.com/@CGPGrey",
    "https://www.youtube.com/@LEMMiNO",
    "https://www.youtube.com/@PolyMatter",
    "https://www.youtube.com/@ColdFusion",
    "https://www.youtube.com/@Nerdwriter1",
    "https://www.youtube.com/@PracticalEngineeringChannel",
    "https://www.youtube.com/@domainofscience",
    "https://www.youtube.com/@BranchEducation",
    "https://www.youtube.com/@upandatom",
    "https://www.youtube.com/@NileRed",
    "https://www.youtube.com/@ScienceAsylum",
    "https://www.youtube.com/@acollierastro",
    "https://www.youtube.com/@eons",
    "https://www.youtube.com/@tibees",
    "https://www.youtube.com/@BobbyBroccoli"
]

CHANNEL_SECTION_SUFFIXES = (
    '/videos',
    '/featured',
    '/shorts',
    '/streams',
    '/playlists',
    '/community',
    '/about',
)


def normalize_channel_url(url: str) -> str:
    normalized_url = url.strip()
    if not normalized_url:
        return ''

    parts = urlsplit(normalized_url)
    netloc = parts.netloc.replace('m.youtube.com', 'www.youtube.com')
    path = parts.path.rstrip('/')

    for suffix in CHANNEL_SECTION_SUFFIXES:
        if path.endswith(suffix):
            path = path[:-len(suffix)]
            break

    path = path.rstrip('/')

    return urlunsplit((parts.scheme, netloc, path, '', ''))



def get_urls() -> list[str]:
    seen: set[str] = set()
    normalized_urls: list[str] = []

    for url in CHANNEL_URLS:
        normalized_url = normalize_channel_url(url)
        if not normalized_url or normalized_url in seen:
            continue
        seen.add(normalized_url)
        normalized_urls.append(normalized_url)

    return normalized_urls
