name: Obtener datos de YouTube diariamente

on:
  schedule:
    - cron: '0 0 * * 1,4-6'  # Ejecuta el trabajo todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear el repositorio
        uses: actions/checkout@v4  # Actualizado a la versión más reciente

      - name: Configurar Python
        uses: actions/setup-python@v4  # Actualizado a la versión más reciente
        with:
          python-version: '3.12.7'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GOOGLE_SHEETS_CREDS_BASE64: ${{ secrets.GOOGLE_SHEETS_CREDS_BASE64 }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python youtube_data.py

      - name: Subir el archivo de logs
        if: always()
        uses: actions/upload-artifact@v4  # Actualizado a la versión más reciente
        with:
          name: logs
          path: youtube_data.log
